### ISSUE TITLE
Last version is breaking permission mechanics

### ISSUE THREAD

**Issue by LilianLem** [aromaa/WorldGuardExtraFlags#217]
Hey,

We're using your plugin to allow members of a LuckPerms group to access features, like flying in a region if they are members of it (combining LuckPerms groups and WorldGuard region groups).
With your last version removing bypass permissions, we can't do this anymore because the notion of permission group is gone, and we can only rely on WorldGuard region groups, which is not enough for our use case.

Is there any replacement we can use for that, or do we need to rollback to the previous version ?

**Comment by aromaa** [comment]
This was intentional change towards being more "WorldGuard native". Whats the reason you are not able to take advantage of WorldGuard groups? The preferred way to do this is to create a region with `passthrough ALLOW` flag, set a group as member of the region and then add the wanted features with the `-g` switch. Any reason you can't take advantage of this, but sounds like you are already doing that? You can also hop on the Discord to discuss your use case
